### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by jkbryan**
Fixed installation section - plus getting the hang of github!

I'll start looking at adding ADLDS now.

### CODE REVIEW

**Comment by jonathanweinberg** [comment]
I'm not the owner of this project, just another participant, but nice work!

**Comment by AndySchneiderDev-zz** [comment]
Rather than re-creating all the functions with the ADLDS noun prefix, I think we could simply add a -server parameter that would default to the local domain on port 389, but would allow someone to specify an ADLDS instance as well.

**Review by AndySchneiderDev-zz — COMMENTED** [review]
I would prefer to add a param to support ADLDS rather than create a duplicate set of functions in the module.

**Comment by jkbryan** [comment]
OK, that's fine - this was only a first stab at getting the method right.

I'll make the necessary changes soon, plus setup the "new" attribute scripts for ADLDS.

Will you reject the pull request? My first time using github, so not that au fait with how this is handled.. :)

**Comment by AndySchneiderDev-zz** [comment]
That would be great. I'll go ahead and reject this one and look for a new one when you get around to it. Thanks a bunch for your help!

**Pull request closed without merging**
